swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo server
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /todo:
    x-swagger-router-controller: todo
    get:
      operationId: todoList
      summary: Získání všech todo
      description: Načte z JSON všechna Todo
      responses:
        200:
          description: List Todo
          schema:
            type: array
            items:
              $ref: "#/definitions/Todo"
    post:
      operationId: todoCreate
      summary: Vytvoření nového Todo
      description: Založí nový objekt a naství mu ID
      parameters:
        - name: todo
          in: body
          description: Částečný 'Todo' objekt
          required: true
          schema:
            type: object
            required:
              - text
            properties:
              text:
                type: string
      responses:
        200:
          description: Vytvořený objekt s ID
          schema:
            $ref: "#/definitions/Todo"
        500:
          description: Error
  /todo/{id}:
    x-swagger-router-controller: todo
    get:
      operationId: todoGet
      summary: Získá Todo dle id
      description: Načte a vrátí Todo dle ID
      parameters:
        - name: id
          type: integer
          in: path
          required: true
      responses:
        200:
          description: Načtený objekt
          schema:
            $ref: "#/definitions/Todo"
        404:
          description: Objekt nebyl nalezen
    put:
      operationId: todoUpdate
      summary: Upraví objekt dle id
      description: Načte, upraví a uloží objekt a jeho updated_at
      parameters:
        - name: id
          type: integer
          in: path
          required: true
        - name: todo
          in: body
          description: Částečný 'Todo' objekt
          required: true
          schema:
            type: object
            required:
              - text
            properties:
              text:
                type: string
      responses:
        200:
          description: Upravený objekt
          schema:
            $ref: "#/definitions/Todo"
        404:
          description: Objekt nebyl nalezen
    delete:
      operationId: todoDelete
      summary: Smaže Todo objekt dle ID
      description: Načte a odstraní objekt dle ID
      parameters:
        - name: id
          type: integer
          in: path
          required: true
      responses:
        200:
          description: OK
        404:
          description: Objekt nebyl nalezen
  /todo/{id}/toggle:
    x-swagger-router-controller: todo
    post:
      operationId: todoToggle
      summary: Změní stav done 
      description: Načte, upraví a uloží stav done objektu a jeho updated_at
      parameters:
        - name: id
          type: integer
          in: path
          required: true
      responses:
        200:
          description: Upravený objekt
          schema:
            $ref: "#/definitions/Todo"
        404:
          description: Objekt nebyl nalezen
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Todo:
    required:
      - text
    type: object
    properties:
      id:
        type: integer
      done:
        type: boolean
      text:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
